Repository alloy-rs/op-alloy, pull requests merged in 2025-03, with the labels that each got.

#463 fix(engine): Empty requests hash
  crates/rpc-types-engine/src/payload/mod.rs
Labels: A-rpc-types-engine, C-bug

#464 chore(consensus): AsRef<OpTxEnvelope>
  crates/consensus/src/transaction/envelope.rs
Labels: A-consensus, C-chore

#465 release: 0.10.9
  CHANGELOG.md
  Cargo.toml
Labels: C-release

#466 chore(deps): alloy 0.12
  Cargo.toml
  crates/consensus/Cargo.toml
  crates/consensus/src/alloy_compat.rs
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/pooled.rs
  crates/consensus/src/transaction/typed.rs
  crates/rpc-types/Cargo.toml
  crates/rpc-types/src/transaction.rs
Labels: C-blocked

#471 feat(rpc-types-engine): Support V4 network payload
  crates/rpc-types-engine/src/envelope.rs
  crates/rpc-types-engine/src/payload/mod.rs
  crates/rpc-types-engine/src/payload/v4.rs
Labels: A-rpc-types-engine, C-feat, H-isthmus

#457 Bump msrv to 1.85
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  clippy.toml
  crates/consensus/src/receipt/envelope.rs
  crates/op-alloy/README.md
  crates/rpc-types-engine/src/payload/mod.rs
Labels: C-deps

#472 fix(l2-withdrawals-root): `OpExecutionPayloadEnvelopeV4` missing v4 payload
  crates/rpc-types-engine/src/payload/v4.rs
Labels: A-rpc-types-engine, C-bug, H-isthmus

#458 Bump edition
  .github/workflows/deps.yml
  Cargo.toml
  crates/consensus/src/alloy_compat.rs
  crates/consensus/src/eip1559.rs
  crates/consensus/src/lib.rs
  crates/consensus/src/receipt/envelope.rs
  crates/consensus/src/receipt/receipts.rs
  crates/consensus/src/source.rs
  crates/consensus/src/transaction/deposit.rs
  crates/consensus/src/transaction/envelope.rs
  crates/consensus/src/transaction/mod.rs
  crates/consensus/src/transaction/pooled.rs
  crates/consensus/src/transaction/tx_type.rs
  crates/consensus/src/transaction/typed.rs
  crates/flz/src/lib.rs
  crates/network/src/lib.rs
  crates/provider/src/ext/engine.rs
  crates/rpc-types-engine/src/attributes.rs
  crates/rpc-types-engine/src/envelope.rs
  crates/rpc-types-engine/src/lib.rs
  crates/rpc-types-engine/src/payload/mod.rs
  crates/rpc-types-engine/src/payload/v4.rs
  crates/rpc-types/src/receipt.rs
  crates/rpc-types/src/transaction.rs
  deny.toml
Labels: C-deps

#473 release: 0.11.2
  CHANGELOG.md
  Cargo.toml
Labels: C-release

#474 chore: Update Dependencies
  Cargo.toml
  crates/consensus/src/receipt/receipts.rs
  crates/consensus/src/transaction/deposit.rs
  crates/rpc-types-engine/Cargo.toml
  crates/rpc-types-engine/src/sidecar.rs
Labels: C-chore

#475 chore: Remove deposit context source
  crates/consensus/src/source.rs
  crates/consensus/src/transaction/deposit.rs
Labels: C-hardfork, C-chore

#482 fix(rpc-types-engine): Fix `PayloadHash` for V3 + V4 topic
  crates/rpc-types-engine/src/envelope.rs
Labels: A-rpc-types-engine, C-bug

#484 chore: remove op-alloy-flz crate and dep
  Cargo.toml
  crates/flz/Cargo.toml
  crates/flz/README.md
  crates/flz/src/lib.rs
Labels: C-deps, C-chore
